Repository seamfix/lib-tt-update-profile, pull requests merged in 2023-10, with the labels that each got.

#7 [MCIV-969] Integrate Update Profile for Re-Identification
  package.json
  src/dto/request.dto.ts
  src/enum/common.enum.ts
  src/update-profile/update-profile.service.spec.ts
  src/update-profile/update-profile.service.ts
Labels: size/L

#8 [MCIV-969] Change response for update profile
  package-lock.json
  src/dto/request.dto.ts
  src/enum/common.enum.ts
  src/update-profile/update-profile.service.spec.ts
  src/update-profile/update-profile.service.ts
Labels: size/M

#9 [MCIV-902a] - Version update.
  package-lock.json
  package.json
Labels: size/XS
